### ISSUE TITLE
Image url is not added to the html

### ISSUE THREAD

**Issue by swapnil1689** [contentstack/json-rte-serializer#38]
Hi,

I have a richtext json which has a image. When I try to convert my richtext json to html the resultant html doesn't have the the url.
I tried using the latest version of the json-rte_serializer.

Please check following screenshots

<img width="904" alt="Screenshot 2024-03-15 at 12 54 27 PM" src="https://github.com/contentstack/json-rte-serializer/assets/1962963/a80e6753-3b1a-4cf8-ac6c-ad52fc707b03">

<img width="917" alt="Screenshot 2024-03-15 at 12 56 41 PM" src="https://github.com/contentstack/json-rte-serializer/assets/1962963/d99c548d-753f-4eff-98be-bb7cdf07f51f">

**Comment by Jayesh2812** [comment]
@swapnil1689 , share the JSON used to convert to HTML and the configuration options used that would help in debugging this issue.

**Comment by swapnil1689** [comment]
[jsonformatter (3).txt](https://github.com/contentstack/json-rte-serializer/files/14615143/jsonformatter.3.txt)
 
@Jayesh2812 , Attaching the json for debuggbing purpose. This is a critical and would appreciate for a quick resolution.

**Comment by swapnil1689** [comment]
What should be configurations so that URL can be extracted?
